name: CI

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs: 
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        users: actions/checkout@v2
      
      - name: Set up Node.js
        users: actions/steup-node@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test